### ISSUE TITLE
2.8.2 fails to build with GHC-7.8.4

### ISSUE THREAD

**Issue by phadej** [yesodweb/persistent#807]
```
Database/Persist/Class/PersistField.hs:142:40:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<>’ (imported from Data.Monoid)
```

I also made a revision http://hackage.haskell.org/package/persistent-2.8.2/revisions/

**Comment by Vlix** [comment]
Oops, that might have been my bad. I think I removed the `Control.Applicative` import out of habit in my PR.

**Comment by parsonsmatt** [comment]
We're dropping GHC <8 support soon. SInce there's already a revision, I consider this closed. Feel free to reopen if you need to :)
