### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [yesodweb/persistent#1344]
```
persistent                > /tmp/stack-06165844a3e2e2dd/persistent-2.13.2.1/Database/Persist/Class/PersistConfig.hs:46:36: error:
persistent                >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
persistent                >                      with: HashMap.HashMap k0 Value
persistent                >       Expected: HashMap.HashMap k0 Value
persistent                >         Actual: aeson-2.0.2.0:Data.Aeson.Types.Internal.Object
persistent                >     • In the second argument of ‘HashMap.lookup’, namely ‘o’
persistent                >       In the expression: HashMap.lookup "left" o
persistent                >       In the expression:
persistent                >         case HashMap.lookup "left" o of
persistent                >           Just v -> Left <$> loadConfig v
persistent                >           Nothing
persistent                >             -> case HashMap.lookup "right" o of
persistent                >                  Just v -> Right <$> loadConfig v
persistent                >                  Nothing
persistent                >                    -> fail "PersistConfig for Either: need either a left or right"
persistent                >    |
persistent                > 46 |         case HashMap.lookup "left" o of
persistent                >    |                                    ^
persistent                > 
persistent                > /tmp/stack-06165844a3e2e2dd/persistent-2.13.2.1/Database/Persist/Class/PersistConfig.hs:49:45: error:
persistent                >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
persistent                >                      with: HashMap.HashMap k1 Value
persistent                >       Expected: HashMap.HashMap k1 Value
persistent                >         Actual: aeson-2.0.2.0:Data.Aeson.Types.Internal.Object
persistent                >     • In the second argument of ‘HashMap.lookup’, namely ‘o’
persistent                >       In the expression: HashMap.lookup "right" o
persistent                >       In the expression:
persistent                >         case HashMap.lookup "right" o of
persistent                >           Just v -> Right <$> loadConfig v
persistent                >           Nothing
persistent                >             -> fail "PersistConfig for Either: need either a left or right"
persistent                >    |
persistent                > 49 |                 case HashMap.lookup "right" o of
persistent                >    |                                             ^
```

**Comment by bergmark** [comment]
Can be closed
