### ISSUE TITLE
persistent-qq-2.12.0.5 testsuite fails to compile with ghc-9.6

### ISSUE THREAD

**Issue by juhp** [yesodweb/persistent#1506]
```
       Building test suite 'specs' for persistent-qq-2.12.0.5..                                                                     
       [5 of 5] Compiling Main                                                                                                      
                                                                                                                                           /var/stackage/work/unpack-dir/unpacked/persistent-qq-2.12.0.5-faf83f6b3c1ec803ae7d1fd37102cb9c1e3d999c7bcc063eea04683707d1579
f/test/Spec.hs:32:20: error: [GHC-88464]                                                                                            
           Variable not in scope: when :: Bool -> IO () -> c                                                                        
          |                                                                                                                         
       32 |   let printDebug = when _debugOn . B.putStrLn . fromLogStr                                                              
          |                    ^^^^
```

**Comment by alaendle** [comment]
Solved by https://github.com/yesodweb/persistent/pull/1487
