### ISSUE TITLE
persistent-redis-2.13.0.2 fails to build with hedis-0.16.1

### ISSUE THREAD

**Issue by juhp** [yesodweb/persistent#1631]
For stackage nightly:
```
       Building library for persistent-redis-2.13.0.2...                                               
       [1 of 7] Compiling Database.Persist.Redis.Config                                                                                                                                                                                                                 
       [2 of 7] Compiling Database.Persist.Redis.Exception                                                                                                                                                                                                              
       [3 of 7] Compiling Database.Persist.Redis.Parser         
       /home/curators/work/unpack-dir/unpacked/persistent-redis-2.13.0.2-a7bc04b4f36b9974663b3db1e1a0e0f273206a4ca21a8ae378209bd48f5c15ed/Database/Persist/Redis/Config.hs:36:18: error: [GHC-76037]                                                                    
           Not in scope: type constructor or class ‘R.PortID’                                                                       
           Note: The module ‘Database.Redis’ does not export ‘PortID’.                                             
          |                                                       
       36 |     rdPort    :: R.PortID, -- ^ Port                                                                                                                                                                                                                        
          |                  ^^^^^^^^                             

       /home/curators/work/unpack-dir/unpacked/persistent-redis-2.13.0.2-a7bc04b4f36b9974663b3db1e1a0e0f273206a4ca21a8ae378209bd48f5c15ed/Database/Persist/Redis/Config.hs:70:48: error: [GHC-76037]                                                                    
           Not in scope: ‘R.connectHost’                          
           Note: The module ‘Database.Redis’ does not export ‘connectHost’.                                                         
           Suggested fix:                                         
             Perhaps use record field of ConnInfo ‘R.connectHooks’ (imported from Database.Redis)
          |                                                       
       70 |         host               <- o .:? "host" .!= R.connectHost R.defaultConnectInfo
          |                                                ^^^^^^^^^^^^^                                                            

       /home/curators/work/unpack-dir/unpacked/persistent-redis-2.13.0.2-a7bc04b4f36b9974663b3db1e1a0e0f273206a4ca21a8ae378209bd48f5c15ed/Database/Persist/Redis/Config.hs:71:48: error: [GHC-76037]                                                                    
           Not in scope: ‘R.connectPort’                          
           Note: The module ‘Database.Redis’ does not export ‘connectPort’.                                                         
          |                                                       
       71 |         port               <- o .:? "port" .!= R.connectPort R.defaultConnectInfo
          |                                                ^^^^^^^^^^^^^                                                            

       /home/curators/work/unpack-dir/unpacked/persistent-redis-2.13.0.2-a7bc04b4f36b9974663b3db1e1a0e0f273206a4ca21a8ae378209bd48f5c15ed/Database/Persist/Redis/Config.hs:87:13: error: [GHC-22385]                                                                    
           Not in scope: record field ‘R.connectHost’
           Note: The module ‘Database.Redis’ does not export ‘connectHost’.                                                         
           Suggested fix:                                         
             Perhaps use record field of ConnInfo ‘R.connectHooks’ (imported from Database.Redis)
          |                                                       
       87 |             R.connectHost = unpack h,
          |             ^^^^^^^^^^^^^            
```

https://github.com/commercialhaskell/stackage/issues/8017
