### ISSUE TITLE
Make it work with ghc-8.0

### ISSUE THREAD

**Issue by erikd** [yesodweb/persistent#553]
GHC 8.0 is about to be released and it seems there have been some substantial changes to the template haskell support.

Building `persistent-template` from git with the ghc-8.0 pre-release results in a huge slew of errors. I'm posting the complete error output here so people don't have to install 8.0 just to see the error messages.

```
Building persistent-template-2.1.6...
Preprocessing library persistent-template-2.1.6...

on the commandline: warning:
    -this-package-key is deprecated: Use -this-unit-id instead

Database/Persist/TH.hs:12:14: warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
[1 of 1] Compiling Database.Persist.TH ( Database/Persist/TH.hs, dist/build/Database/Persist/TH.o )

Database/Persist/TH.hs:402:5: error:
    • Couldn't match expected type ‘Dec’ with actual type ‘Cxt -> Dec’
    • In the expression:
        DataD [] nameFinal paramsFinal constrs
        $ map (mkName . unpack) $ entityDerives t
      In an equation for ‘dataTypeDec’:
          dataTypeDec mps t
            = DataD [] nameFinal paramsFinal constrs
              $ map (mkName . unpack) $ entityDerives t
            where
                mkCol x fd@(FieldDef {..})
                  = (mkName $ unpack $ recName mps x fieldHaskell, 
                     if fieldStrict then IsStrict else NotStrict, 
                     maybeIdType mps fd Nothing Nothing)
                (nameFinal, paramsFinal)
                  | mpsGeneric mps = (nameG, [PlainTV backend])
                  | otherwise = (name, [])
                nameG
                  = mkName $ unpack $ unHaskellName (entityHaskell t) ++ "Generic"
                name = mkName $ unpack $ unHaskellName $ entityHaskell t
                ....

Database/Persist/TH.hs:402:36: error:
    • Couldn't match expected type ‘Maybe Kind’
                  with actual type ‘[Con]’
    • In the fourth argument of ‘DataD’, namely ‘constrs’
      In the expression: DataD [] nameFinal paramsFinal constrs
      In the expression:
        DataD [] nameFinal paramsFinal constrs
        $ map (mkName . unpack) $ entityDerives t

Database/Persist/TH.hs:403:7: error:
    • Couldn't match type ‘Name’ with ‘Con’
      Expected type: [Con]
        Actual type: [Name]
    • In the second argument of ‘($)’, namely
        ‘map (mkName . unpack) $ entityDerives t’
      In the expression:
        DataD [] nameFinal paramsFinal constrs
        $ map (mkName . unpack) $ entityDerives t
      In an equation for ‘dataTypeDec’:
          dataTypeDec mps t
            = DataD [] nameFinal paramsFinal constrs
              $ map (mkName . unpack) $ entityDerives t
            where
                mkCol x fd@(FieldDef {..})
                  = (mkName $ unpack $ recName mps x fieldHaskell, 
                     if fieldStrict then IsStrict else NotStrict, 
                     maybeIdType mps fd Nothing Nothing)
                (nameFinal, paramsFinal)
                  | mpsGeneric mps = (nameG, [PlainTV backend])
                  | otherwise = (name, [])
                nameG
                  = mkName $ unpack $ unHaskellName (entityHaskell t) ++ "Generic"
                name = mkName $ unpack $ unHaskellName $ entityHaskell t
                ....

Database/Persist/TH.hs:407:30: error:
    • Data constructor not in scope: IsStrict
    • Perhaps you meant ‘Strict’ (imported from Language.Haskell.TH.Syntax)

Database/Persist/TH.hs:407:44: error:
    Data constructor not in scope: NotStrict

Database/Persist/TH.hs:424:11: error:
    Data constructor not in scope: NotStrict :: Bang

Database/Persist/TH.hs:437:5: error:
    • Couldn't match expected type ‘Dec’ with actual type ‘Cxt -> Dec’
    • Probable cause: ‘DataInstD’ is applied to too few arguments
      In the expression:
        DataInstD
          []
          ''Unique
          [genericDataType mps (entityHaskell t) backendT]
          (map (mkUnique mps t) $ entityUniques t)
          []
      In an equation for ‘uniqueTypeDec’:
          uniqueTypeDec mps t
            = DataInstD
                []
                ''Unique
                [genericDataType mps (entityHaskell t) backendT]
                (map (mkUnique mps t) $ entityUniques t)
                []

Database/Persist/TH.hs:439:14: error:
    • Couldn't match expected type ‘Maybe Kind’
                  with actual type ‘[Con]’
    • In the fourth argument of ‘DataInstD’, namely
        ‘(map (mkUnique mps t) $ entityUniques t)’
      In the expression:
        DataInstD
          []
          ''Unique
          [genericDataType mps (entityHaskell t) backendT]
          (map (mkUnique mps t) $ entityUniques t)
          []
      In an equation for ‘uniqueTypeDec’:
          uniqueTypeDec mps t
            = DataInstD
                []
                ''Unique
                [genericDataType mps (entityHaskell t) backendT]
                (map (mkUnique mps t) $ entityUniques t)
                []

Database/Persist/TH.hs:453:19: error:
    Data constructor not in scope: NotStrict :: Strict

Database/Persist/TH.hs:696:52: error:
    • Couldn't match expected type ‘Maybe Kind’ with actual type ‘Con’
    • In the fourth argument of ‘NewtypeInstD’, namely ‘dec’
      In the expression: NewtypeInstD [] k [recordType] dec i
      In the expression:
        if useNewtype then
            NewtypeInstD [] k [recordType] dec i
        else
            DataInstD [] k [recordType] [dec] i

Database/Persist/TH.hs:696:56: error:
    • Couldn't match expected type ‘Con’ with actual type ‘[Name]’
    • In the fifth argument of ‘NewtypeInstD’, namely ‘i’
      In the expression: NewtypeInstD [] k [recordType] dec i
      In the expression:
        if useNewtype then
            NewtypeInstD [] k [recordType] dec i
        else
            DataInstD [] k [recordType] [dec] i

Database/Persist/TH.hs:697:52: error:
    • Couldn't match expected type ‘Maybe Kind’
                  with actual type ‘[Con]’
    • In the fourth argument of ‘DataInstD’, namely ‘[dec]’
      In the expression: DataInstD [] k [recordType] [dec] i
      In the expression:
        if useNewtype then
            NewtypeInstD [] k [recordType] dec i
        else
            DataInstD [] k [recordType] [dec] i

Database/Persist/TH.hs:697:58: error:
    • Couldn't match type ‘Name’ with ‘Con’
      Expected type: [Con]
        Actual type: [Name]
    • In the fifth argument of ‘DataInstD’, namely ‘i’
      In the expression: DataInstD [] k [recordType] [dec] i
      In the expression:
        if useNewtype then
            NewtypeInstD [] k [recordType] dec i
        else
            DataInstD [] k [recordType] [dec] i

Database/Persist/TH.hs:698:5: error:
    • Couldn't match type ‘Cxt -> Dec’ with ‘Dec’
      Expected type: Q (Dec, [Dec])
        Actual type: Q (Cxt -> Dec, [Dec])
    • In a stmt of a 'do' block: return (kd, instDecs)
      In the expression:
        do { (instDecs, i) <- if mpsGeneric mps then
                                  if not useNewtype then do { ... } else do { ... }
                              else
                                  if not useNewtype then do { ... } else do { ... };
             let kd = ...;
             return (kd, instDecs) }
      In an equation for ‘mkKeyTypeDec’:
          mkKeyTypeDec mps t
            = do { (instDecs, i) <- if mpsGeneric mps then
                                        if not useNewtype then ... else ...
                                    else
                                        if not useNewtype then ... else ...;
                   let kd = ...;
                   return (kd, instDecs) }
            where
                keyConE = keyConExp t
                unKeyE = unKeyExp t
                dec = RecC (keyConName t) (keyFields mps t)
                k = ''Key
                ....

Database/Persist/TH.hs:831:33: error:
    Data constructor not in scope: NotStrict

Database/Persist/TH.hs:833:26: error:
    Data constructor not in scope: NotStrict

Database/Persist/TH.hs:958:11: error:
    • Couldn't match expected type ‘Dec’ with actual type ‘Cxt -> Dec’
    • Probable cause: ‘DataInstD’ is applied to too few arguments
      In the expression:
        DataInstD
          []
          ''EntityField
          [genDataType, VarT $ mkName "typ"]
          (map fst fields)
          []
      In the second argument of ‘($)’, namely
        ‘[uniqueTypeDec mps t, keyTypeDec, keyToValues', keyFromValues',
          ....]’
      In the expression:
        InstanceD instanceConstraint clazz
        $ [uniqueTypeDec mps t, keyTypeDec, keyToValues', keyFromValues',
           ....]

Database/Persist/TH.hs:964:14: error:
    • Couldn't match expected type ‘Maybe Kind’
                  with actual type ‘[Con]’
    • In the fourth argument of ‘DataInstD’, namely ‘(map fst fields)’
      In the expression:
        DataInstD
          []
          ''EntityField
          [genDataType, VarT $ mkName "typ"]
          (map fst fields)
          []
      In the second argument of ‘($)’, namely
        ‘[uniqueTypeDec mps t, keyTypeDec, keyToValues', keyFromValues',
          ....]’
```

**Comment by erikd** [comment]
The TH changes for this release are listed here : 
https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0#template-haskell-2.11.0.0

**Comment by erikd** [comment]
I'm currently working on this issue. So far, it seems reasonably straight forward.

**Comment by gregwebs** [comment]
thanks!

**Comment by erikd** [comment]
The migration guide does not quite provide sufficient information for me to fix this. I've asked a question on the ghc-devs list asking for some clarification.

**Comment by erikd** [comment]
I've got some code that compiles and passes tests with ghc-7.10, and also compiles with ghc-8.0 but a tooling issue prevents me from running the tests. I'm currently debugging that.

**Comment by gregwebs** [comment]
Stack test should work. Also Travis ci should work

**Comment by erikd** [comment]
It was a bad interaction between cabal and ghc-8.0. Thats resolved now, but I still need to make it pass the tests with ghc-8.0 :-).

**Comment by erikd** [comment]
https://github.com/yesodweb/persistent/pull/554

**Comment by erikd** [comment]
The PR has been merged.

**Comment by erikd** [comment]
Any ETA on a new release so I can continue working through ghc-8.0 support for the rest of the yesod stack?

**Comment by MaxGabriel** [comment]
If you use Stack, you can use use master of this repo by [specifying a git repo and commit](http://docs.haskellstack.org/en/stable/yaml_configuration/), I think it would look like this:

```yaml
packages:
- location:
    git: git@github.com:yesodweb/persistent.git
    commit: cef6f6fc1a07ca9ffd4da1f162527fa932f70511
```

**Comment by erikd** [comment]
@MaxGabriel Unfortunately that does not help getting Esqueleto working with GHC due to git HEAD having the `BaseBackend` changes.

What's really needed is a new version of persistent *without* the `BaseBackend` related changes but with the ghc-8.0 support and another with the `BaseBackend` changes.
