### ISSUE TITLE
error building persistent-sqlite-2.13.3.1 with ghc-10.0.0.20260917:  __STDC_VERSION__ does not advertise C11, C++11 or later

### ISSUE THREAD

**Issue by jwaldmann** [yesodweb/persistent#1641]
I am trying to build with ghc-10.0.1-alpha1 (recently published)

```
$ cabal install persistent-sqlite-2.13.3.1  -w /opt/ghc/ghc-10.0.0.20260917/bin/ghc --allow-newer --constraint hashable==1.5.0.0

...

Configuring library for persistent-sqlite-2.13.3.1...
[1 of 3] Compiling Database.Sqlite.Internal ( Database/Sqlite/Internal.hs, dist/build/Database/Sqlite/Internal.o, dist/build/Database/Sqlite/Internal.dyn_o )
[2 of 3] Compiling Database.Sqlite  ( Database/Sqlite.hs, dist/build/Database/Sqlite.o, dist/build/Database/Sqlite.dyn_o )
In file included from /opt/ghc/ghc-10.0.0.20260917/lib/ghc-10.0.0.20260917/lib/../lib/x86_64-linux-ghc-10.0.0.20260917-inplace/rts-1.0.3/include/Rts.h:38,
                 from /tmp/ghc93749_tmp_0_0/ghc_tmp_122_1.c:1:0: error:
    

/opt/ghc/ghc-10.0.0.20260917/lib/ghc-10.0.0.20260917/lib/../lib/x86_64-linux-ghc-10.0.0.20260917-inplace/rts-1.0.3/include/Stg.h:35:3: error:
     error: #error __STDC_VERSION__ does not advertise C11, C++11 or later
       35 | # error __STDC_VERSION__ does not advertise C11, C++11 or later
          |   ^~~~~
   |
35 | # error __STDC_VERSION__ does not advertise C11, C++11 or later
   |   ^

<no location info>: error:
    `cc' failed in phase `C Compiler'. (Exit code: 1)
```

with gcc-16.2.1 (comes with current Fedora 44)

Compilation is fine with ghc-9.14.1 and ghc-9.14.1.20260916. So perhaps it is a ghc problem.
