### ISSUE TITLE
persistent-th with ghc-9 (th-2.17)?

### ISSUE THREAD

**Issue by jwaldmann** [yesodweb/persistent#1198]
This does not currently work? (I did not see PR or issue, so perhaps the following is useful).

When compiling persistent-th-2.12.0.0 with ghc-9.0, I get 
```
Database/Persist/TH.hs:280:17: error:
    • Couldn't match type ‘TExp a3’ with ‘SqlTypeExp’
      Expected: SqlTypeExp -> Code m SqlTypeExp
        Actual: SqlTypeExp -> Code m (TExp a3)
    • In the expression: unsafeTExpCoerce . lift
      In an equation for ‘liftTyped’: liftTyped = unsafeTExpCoerce . lift
      In the instance declaration for ‘Lift SqlTypeExp’
    |
280 |     liftTyped = unsafeTExpCoerce . lift
    |                 ^^^^^^^^^^^^^^^^^^^^^^^
```
Here, the type changed (TH-2.16: https://hackage.haskell.org/package/template-haskell-2.16.0.0/docs/Language-Haskell-TH-Syntax.html#v:unsafeTExpCoerce , TH-2.17:
https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/template-haskell/Language/Haskell/TH/Syntax.hs#L361 , see remark on `Quote m` in the source)

Also,
```
Database/Persist/TH.hs:600:31: error:
    • Couldn't match type: flag0 -> TyVarBndr flag0
                     with: TyVarBndr ()
      Expected: [TyVarBndr ()]
        Actual: [flag0 -> TyVarBndr flag0]
    • In the third argument of ‘DataD’, namely ‘paramsFinal’
      In the second argument of ‘($)’, namely
        ‘DataD
           [] nameFinal paramsFinal Nothing constrs
           (stockDerives <> anyclassDerives)’
```
where
```
TH-2.16:  DataD Cxt Name [TyVarBndr] (Maybe Kind) [Con] [DerivClause]
TH-2.17:  DataD Cxt Name [TyVarBndr ()]           (Maybe Kind)             [Con] [DerivClause]
```
where `TyVarBndr` aquired a type argument.

and later,
```
Database/Persist/TH.hs:1544:43: error:
    • Couldn't match expected type ‘Exp’
                  with actual type ‘[Stmt] -> Exp’
    • Probable cause: ‘DoE’ is applied to too few arguments
      In the second argument of ‘normalClause’, namely ‘(DoE stmts)’
      In the expression: normalClause [VarP key] (DoE stmts)
```
where
```
TH-2.16: DoE [Stmt]
TH-2.17: DoE (Maybe ModName) [Stmt] 
```
because of QualifiedDo

**Comment by jwaldmann** [comment]
previous commit allows to build with ghc-9.0.1 (only - still needs some `#ifdef`-ing around `DoE` and `PlainTV` for backward compatibility)

**Comment by parsonsmatt** [comment]
Great catch - I'll put some Hackage revisions up to prevent folks from running into this.

**Comment by sjakobi** [comment]
I'm still running into the build failure. AFAIK at least v2.8.2.3 and up need revisions.

I can recommend [`hackage-cli`](https://github.com/hackage-trustees/hackage-cli) for easily creating multiple revisions at once.

**Comment by parsonsmatt** [comment]
@sjakobi can you link a guide on how to do that? I couldn't tell from reading the README how to do that

**Comment by sjakobi** [comment]
I'm not aware of a guide, but I'd do it like this:

```
$ mkdir fresh
$ cd fresh
$ hackage-cli pull-cabal persistent-template '>= 2.8.2.3'
...
skipped excluded 2.8.2.2
saved persistent-template-2.8.2.3.cabal (2875 bytes)
saved persistent-template-2.8.3.0.cabal (2864 bytes)
saved persistent-template-2.8.3.1.cabal (2864 bytes)
saved persistent-template-2.9.cabal (2875 bytes)
saved persistent-template-2.9.1.0.cabal (3008 bytes)
saved persistent-template-2.12.0.0.cabal (1008 bytes)
$ hackage-cli add-bound template-haskell '<2.17' *
Edit failed, version ranges don't match:  >1 && <1 && <2.17 =/= <2.17
```

This is a weird error, which apparently refers to v2.12.0.0, which doesn't depend on `template-haskell` at all.

Now try pushing the revisions in the default review mode:

```
$ hackage-cli push-cabal --incr-rev *
Using Hackage credentials for username "sjakobi"
Pushing "persistent-template-2.8.2.3.cabal" (persistent-template-2.8.2.3~3) [review-mode] ...
Hackage response was (after 0.300 secs):
================================================================================
Changes:

<ul>
  
 * Changed the library component&#39;s library dependency on &#39;template-haskell&#39;
                          from `>=2.11 && <2.17`
                          to `<2.17 && >=2.11 && <2.17`

</ul>
================================================================================
Pushing "persistent-template-2.8.3.0.cabal" (persistent-template-2.8.3.0~2) [review-mode] ...
Hackage response was (after 0.292 secs):
================================================================================
Changes:

<ul>
  
 * Changed the library component&#39;s library dependency on &#39;template-haskell&#39;
                          from `>=2.11`
                          to `<2.17 && >=2.11`

</ul>
================================================================================
Pushing "persistent-template-2.8.3.1.cabal" (persistent-template-2.8.3.1~1) [review-mode] ...
Hackage response was (after 0.722 secs):
================================================================================
Changes:

<ul>
  
 * Changed the library component&#39;s library dependency on &#39;template-haskell&#39;
                          from `>=2.11`
                          to `<2.17 && >=2.11`

</ul>
================================================================================
Pushing "persistent-template-2.9.1.0.cabal" (persistent-template-2.9.1.0~2) [review-mode] ...
Hackage response was (after 0.746 secs):
================================================================================
Changes:

<ul>
  
 * Changed the library component&#39;s library dependency on &#39;template-haskell&#39;
                          from `>=2.11 && <2.17`
                          to `<2.17 && >=2.11 && <2.17`

</ul>
================================================================================
Pushing "persistent-template-2.9.cabal" (persistent-template-2.9~2) [review-mode] ...
Hackage response was (after 0.749 secs):
================================================================================
Changes:

<ul>
  
 * Changed the library component&#39;s library dependency on &#39;template-haskell&#39;
                          from `>=2.11 && <2.17`
                          to `<2.17 && >=2.11 && <2.17`

</ul>
================================================================================
Pushing "persistent-template-2.12.0.0.cabal" (persistent-template-2.12.0.0~0) [review-mode] ...
Hackage response was (after 0.711 secs):
================================================================================
Errors:

Only trivial changes, don&#39;t bother making this revision.

================================================================================
```

If you look at the change summaries, only those for v2.8.3.0 and v2.8.3.1 seem to add value, so we only publish these:

```
$ hackage-cli push-cabal --incr-rev --publish persistent-template-2.8.2.3.cabal persistent-template-2.8.3.0.cabal
```

**Comment by jwaldmann** [comment]
I was not aware of "This package was absorbed into persistent with the 2.12.0.1 release" on https://hackage.haskell.org/package/persistent-template. 

Does that solve the problem (cannot compile with ghc-9)? Apparently not, as https://hackage.haskell.org/package/persistent-2.12.1.0/persistent.cabal still has `template-haskell         >= 2.11 && < 2.17`.

So what do I do when I want to build with ghc-9? (Except using my fork.) Is  "add hackage revision" supposed to help with that?

**Comment by parsonsmatt** [comment]
If you have a fork of `persistent` that builds with GHC 9, I'd love a PR :) 

Last I tried, I had problems with upstream dependencies - `basement` isn't building with GHC9 either.

**Comment by jwaldmann** [comment]
https://github.com/jwaldmann/persistent/commit/45b1961163dac352bc5bfae65cf5e86282acabbc (already linked above). Worksforme. Well, at least it builds, it's part of a larger project, I didn't really test the persistent part recently.

I use it like this https://gitlab.imn.htwk-leipzig.de/waldmann/pure-matchbox/-/blob/master/cabal.project#L59

But it's not ready for a PR
* this is forked at 2.12.0.0 (before persistent-template was merged into persistent)
* it ONLY builds with ghc-9 (not ghc-8) - would need CPP to switch in the source?
