### ISSUE TITLE
how to handle: PersistEntity ... does not have a default primary key? (persistent-2.14)

### ISSUE THREAD

**Issue by jwaldmann** [yesodweb/persistent#1442]
I have this code that stopped working with  `persistent-2.14.*` while it worked before (stackage nightly of today, vs. LTS up to 20)
```
Schule sql=schule
  Id                                     sql=UNr
  name              Text                 sql=Name
...
```
I am getting
```
/home/waldmann/space/all/yesod/Foundation.hs:280:26: error:
    • The PersistEntity Schule does not have a default primary key.
      This means that 'insert' will fail with a database error.
      Please  provide a default= clause inthe entity definition,
      or use 'insertKey' instead to provide one.
    • In the second argument of ‘($)’, namely ‘insert schule’
      In a stmt of a 'do' block: key <- runDB $ insert schule
      In the expression:        
        do let schule = Schule name (Just "") True Sprache.DE (Just name)
           key <- runDB $ insert schule
           return key           
    |                           
280 |           key <- runDB $ insert schule
    |                          ^^^^^^
                                
```
When I delete the line that contains `Id`, the error goes away. But I need that column name because I have legacy data.

**Comment by parsonsmatt** [comment]
This is a bug, thanks for reporting!

**Comment by parsonsmatt** [comment]
In the mean time, work around would be to use a `default=` expression. If you're using `persistent` migrations then you'll need to match what the database tells you, but otherwise you can use anything.
